import { Routes } from '@angular/router'
import {
	AccountDetailsComponent,
	AccountsComponent,
	AddressBookComponent,
	ConfigureAppComponent,
	ConfigureWalletComponent,
	ConverterComponent,
	ImportAddressBookComponent,
	ImportWalletComponent,
	KeygeneratorComponent,
	ManageRepresentativesComponent,
	ManageWalletComponent,
	MultisigComponent,
	QrGeneratorComponent,
	QrScanComponent,
	ReceiveComponent,
	RemoteSigningComponent,
	RepresentativesComponent,
	SendComponent,
	SignComponent,
	SweeperComponent,
	TransactionDetailsComponent,
	WalletsComponent,
	WelcomeComponent,
} from 'app/components'

export const routes: Routes = [
	{ path: '', component: WelcomeComponent },
	{ path: 'accounts', component: AccountsComponent },
	{ path: 'accounts/:account', component: AccountDetailsComponent },
	{ path: 'address-book', component: AddressBookComponent },
	{ path: 'configure-app', component: ConfigureAppComponent },
	{ path: 'configure-wallet', component: ConfigureWalletComponent },
	{ path: 'converter', component: ConverterComponent },
	{ path: 'import-address-book', component: ImportAddressBookComponent },
	{ path: 'import-wallet', component: ImportWalletComponent },
	{ path: 'keygenerator', component: KeygeneratorComponent },
	{ path: 'manage-representatives', component: ManageRepresentativesComponent },
	{ path: 'manage-wallet', component: ManageWalletComponent },
	{ path: 'multisig', component: MultisigComponent },
	{ path: 'qr-generator', component: QrGeneratorComponent },
	{ path: 'qr-scan', component: QrScanComponent },
	{ path: 'receive', component: ReceiveComponent },
	{ path: 'remote-signing', component: RemoteSigningComponent },
	{ path: 'representatives', component: RepresentativesComponent },
	{ path: 'send', component: SendComponent },
	{ path: 'sign', component: SignComponent },
	{ path: 'sweeper', component: SweeperComponent },
	{ path: 'transaction/:transaction', component: TransactionDetailsComponent },
	{ path: 'wallets', component: WalletsComponent },
]
